build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: true
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    max: 4
    excludeGuardClauses: true
  ForbiddenComment:
    active: true
    comments:
      - value: 'STOPSHIP:'
        reason: 'Remove before merging.'
  WildcardImport:
    active: true
    excludeImports:
      - 'androidx.compose.ui.graphics.*'
      - 'androidx.compose.foundation.layout.*'

potential-bugs:
  LateinitUsage:
    active: false
